### PR TITLE
Support 32-bit windows for conda-unpack.exe

### PR DESCRIPTION
**Pull request by johanjeppsson**

### CODE REVIEW

**Comment by msarahan** [comment]
@cla-bot check

**Comment by johanjeppsson** [comment]
Are there any tips on how to debug the tests? Can I run them on my branch to figure out what is going on?

**Comment by johanjeppsson** [comment]
Does anyone have any feedback on this? Is there anything else I should do?

**Comment by xhochy** [comment]
@johanjeppsson Can you rebase on master? Some tests will keep failing but as long as these are the same ones on master, we can merge.

**Comment by johanjeppsson** [comment]
I think I rebased by change succesfully, but I haven't done this on forked github repos before, so please let me know if it doesn't look right!

**Comment by xhochy** [comment]
It looks right, sadly we currently have a problem with tests on master and thus we don't see if the code still passes.

**Comment by mcg1969** [comment]
Better late than never, I hope. Thank you for the submission!

**Comment by mcg1969** [comment]
It would be good if we can add an appveyor entry for the 32-bit case, but I don't mind merging without it

**Pull request merged**
