### PR TITLE
bugfix: ensure conda-unpack is executable

### PR DESCRIPTION
**Pull request by morotti**
### Description

ensure conda-unpack is executable. 
a file must have both readable and executable flags to be executable.

### Checklist

I didn't find any example to add a news or modify the release notes? If something is needed, can you add or explain me what to add precisely.

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
- [X] Add / update necessary tests?
- [X] Add / update outdated documentation?

### CODE REVIEW

**Comment by xhochy** [comment]
@morotti Have you signed the CLA? If so, I would ping someone from Anaconda again.

**Comment by morotti** [comment]
@xhochy thank you for getting back

I've read the CLA and it's not applicable, I do not intend to sign it.
My contribution is changing 3 characters, fixing a typo is not subject to copyrights or patents. The legal document I was sent is irrelevant at best.

You're welcome to merge this PR as-is or you're welcome to make your own commit to fix the typo, whatever is easier for you =)

**Comment by xhochy** [comment]
@jezdez Any suggestions on how to proceed here?

**Comment by marcelotrevisani** [comment]
> @jezdez Any suggestions on how to proceed here?

As far as I know, If the developer does not agree with the CLA this can't be merged then.

**Comment by xhochy** [comment]
The question here is whether someone else can now contribute this fix. It's so minimal, it's probably not covered under any copyright.

**Comment by marcelotrevisani** [comment]
I would not use raw hexadecimals as well. If someone want to change it and put it to use the ``stat`` constants it would be better, something like

```python
combined_permission = stat.S_IRUSR | stat.S_IXUSR | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH
os.chmod(fil.name, st.st_mode | combined_permission)
```

**Comment by jezdez** [comment]
> It's so minimal, it's probably not covered under any copyright.

Copyright doesn't work like that, the person contributing the PR has the copyright to this change and would, by signing the CLA, assign it to Anaconda Inc.

But: we're in the process to change the CLA to benefit NumFOCUS, so the OP might be more inclined to sign that.

Meanwhile, it's not acceptable to merge this PR as-is.

**Pull request closed without merging**
