### PR TITLE
activate.fish: support activating conda in fish shells

### PR DESCRIPTION
**Pull request by d4l3k**
### Description

This adds support for the fish shell #72

Test plan:

```
$ pytest conda_pack/tests/test_core.py
```
manual tests
```
$ conda-pack
$ tar xvf ~/conda-pack/conda-pack-3.10.tar.gz; . bin/activate.fish
$ which python3
$ deactivate
```

### Checklist - did you ...

- [ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

**Comment by d4l3k** [comment]
I signed the CLA

@conda-bot

**Comment by xhochy** [comment]
@d4l3k The tests are sadly failing in CI

**Comment by d4l3k** [comment]
@xhochy tests should be passing now -- I added fish as a conda-forge dep to the tests worklfow

**Comment by xhochy** [comment]
It still fails, we probably need to skip it on Windows.

**Comment by d4l3k** [comment]
@xhochy updated it to only install fish on mac/linux. test_activate is passing on mac/linux. 

The failing mac test only failed on Py3.8 and seems to be flakiness unrelated to this PR.

**Comment by d4l3k** [comment]
@xhochy seems like all but 1 test is passing now. Looking at that failure I'm not sure how this PR could have caused it since I don't think I touched anything related to that file. Would appreciate your help in debugging this

**Comment by xhochy** [comment]
Everything looks good now, needs someone to merge the CLA though (I cannot do that)

**Comment by travishathaway** [comment]
@conda-bot check

**Comment by travishathaway** [comment]
Should be good to go. Sorry for the delay!

**Review by xhochy — APPROVED** [review]

**Pull request merged**
