### PR TITLE
Ignore missing files in the source conda environment

### LINKED ISSUE #85: Packing fails despite excluding files
If you trim down your environment by e.g. removing all static library archives, `conda-pack` is unable to package this environment. This is also the case when repacking an environment that previously went through `conda-pack` but where exclusions where used in packing the environment.

Reproducible example:

```
conda create -p $(pwd)/test-env conda-pack python=3.7
conda activate $(pwd)/test-env
conda-pack --exclude '*.a' -o env.tar.gz
mkdir other-env
cd other-env
source bin/activate
conda-pack --exclude '*.a' -o env.tar.gz
```

which leads to the following error:

```
Collecting packages...
CondaPackError:
Files managed by conda were found to have been deleted/overwritten in the
following packages:

- bzip2='1.0.8'
- readline='8.0'
- python='3.7.3'
- libcxxabi='8.0.0'
- libcxx='8.0.0'
- xz='5.2.4'
- zlib='1.2.11'
- tk='8.6.9'
- libffi='3.2.1'
- ncurses='6.1'
- sqlite='3.29.0'

This is usually due to `pip` uninstalling or clobbering conda managed files,
resulting in an inconsistent environment. Please check your environment for
conda/pip conflicts using `conda list`, and fix the environment by ensuring
only one version of each package is installed (conda preferred).
```

A possible solution would be to do the integrity checks on the call to `pack` and not during loading the environment. @jcrist would that be an acceptable solution for you?

### PR DESCRIPTION
**Pull request by xhochy**
Fixes #85

This also updates conda-pack to be compatible with the latest conda releases.

### CODE REVIEW

**Comment by xhochy** [comment]
Signed the CLA quite a while ago but it was probably never imported.

**Comment by jjhelmus** [comment]
@cla-bot check

**Comment by jjhelmus** [comment]
> Signed the CLA quite a while ago but it was probably never imported.

Sorry about that, fixed now.

**Comment by xhochy** [comment]
@jjhelmus This is ready for review and also fixes the tests on Linux. I did some debugging on the Windows issues but failed there as the archive implementation is behaving quite weird. The `conda-unpack*` scripts are definitely part of the file list when the archive is being created but once it is saved to disk and reloaded, all the files that were added in the `finish` function are missing from the archive.

**Comment by jjhelmus** [comment]
Looks good to me.  The failing tests on Windows are not good but seem to be unrelated to this work, I'll create a issue to investigate them further.

**Pull request merged**
