### PR TITLE
fix(#80): replace python path reference properly for binary files

### PR DESCRIPTION
**Pull request by frascuchon**
This PR apply comments discussed in issue  #80  and fixes it.

### CODE REVIEW

**Comment by xhochy** [comment]
@frascuchon Can you rebase on master?

Also did you already sign the CLA?

**Comment by frascuchon** [comment]
> @frascuchon Can you rebase on master?

Done!

> Also did you already sign the CLA?

Yes, indeed, I've done that process several times.

**Comment by xhochy** [comment]
@jjhelmus Now we also see the `Files managed by conda were found to have been deleted/overwritten` issue on Linux. Could this be a problem with a file collision with the `python-feedstock` in general in `defaults`?

```
E           Files managed by conda were found to have been deleted/overwritten in the
E           following packages:
E           
E           - python='3.8.2'
E           
E           This is usually due to `pip` uninstalling or clobbering conda managed files,
E           resulting in an inconsistent environment. Please check your environment for
E           conda/pip conflicts using `conda list`, and fix the environment by ensuring
E           only one version of each package is installed (conda preferred).
conda_pack\core.py:781: CondaPackException

```

**Comment by marcelotrevisani** [comment]
Is it possible to create a test for it?

**Comment by mcg1969** [comment]
Completing with #122

**Pull request closed without merging**
