### PR TITLE
Prepare changelog for 0.7.1

### PR DESCRIPTION
**Pull request by xhochy**

### CODE REVIEW

**Comment by jaimergp** [comment]
Hm, it looks like we don't have a [rever config](https://github.com/conda/conda/blob/main/rever.xsh) here to generate the changelog. You can check `conda/conda` for the general instructions for [releases](https://github.com/conda/conda/blob/main/RELEASE.md). We should have received an automated PR adding it to the repo.

**Comment by xhochy** [comment]
Yes, I'm a bit confused and looked at other projects like `conda-index` and it seems like also there the files in `news/´ just starve.

**Comment by jaimergp** [comment]
On the other hand, we haven't had it ever in this repo so I guess it's ok to re-use the autogenerated changelog from the GH releases and then copy the news on top? Not sure how we want to proceed here.

**Comment by xhochy** [comment]
The automated changelog (with bots removed) would be:

```
## What's Changed
* Empty commit to trigger ctools dev release upload by @dbast in https://github.com/conda/conda-pack/pull/205
* Updates tests to Python 3.7/3.10, as 2.7/3.6 being EOL by @dbast in https://github.com/conda/conda-pack/pull/207
* Renovations and require Python >=3.7 by @dbast in https://github.com/conda/conda-pack/pull/206
* document packaging of environments as self-extracting executables by @saraedum in https://github.com/conda/conda-pack/pull/159
* Add fix for core.py missing space by @Rtanti in https://github.com/conda/conda-pack/pull/218
* Remove `boards.yml` by @kenodegard in https://github.com/conda/conda-pack/pull/227
* Rename master to main by @kenodegard in https://github.com/conda/conda-pack/pull/232
* Create CODEOWNERS by @jezdez in https://github.com/conda/conda-pack/pull/233
* Chore: Update main.yml action versions, upgrade from deprecated syntax, fix badge url by @dbast in https://github.com/conda/conda-pack/pull/250
* Re-enable coverage reporting by @dbast in https://github.com/conda/conda-pack/pull/251
* Add @xhochy to CODEOWNERS by @xhochy in https://github.com/conda/conda-pack/pull/259
* Allow the compression level to be set in zip files by @jjhelmus in https://github.com/conda/conda-pack/pull/252
* Fix path separator on Windows distributions by @andysham in https://github.com/conda/conda-pack/pull/275
* codesign binaries on osx-arm64 by @xhochy in https://github.com/conda/conda-pack/pull/257

## New Contributors
* @saraedum made their first contribution in https://github.com/conda/conda-pack/pull/159
* @Rtanti made their first contribution in https://github.com/conda/conda-pack/pull/218
* @kenodegard made their first contribution in https://github.com/conda/conda-pack/pull/227
* @jezdez made their first contribution in https://github.com/conda/conda-pack/pull/233
* @jjhelmus made their first contribution in https://github.com/conda/conda-pack/pull/252
* @andysham made their first contribution in https://github.com/conda/conda-pack/pull/275
```

**Comment by jaimergp** [comment]
There are a few items there that are just changing repo internals, so I'd say we remove those (e.g. "Remove `boards.yml") too. In other words:

```
## What's Changed
* Updates tests to Python 3.7/3.10, as 2.7/3.6 being EOL by @dbast in https://github.com/conda/conda-pack/pull/207
* Renovations and require Python >=3.7 by @dbast in https://github.com/conda/conda-pack/pull/206
* document packaging of environments as self-extracting executables by @saraedum in https://github.com/conda/conda-pack/pull/159
* Add fix for core.py missing space by @Rtanti in https://github.com/conda/conda-pack/pull/218
* Re-enable coverage reporting by @dbast in https://github.com/conda/conda-pack/pull/251
* Allow the compression level to be set in zip files by @jjhelmus in https://github.com/conda/conda-pack/pull/252
* Fix path separator on Windows distributions by @andysham in https://github.com/conda/conda-pack/pull/275
* codesign binaries on osx-arm64 by @xhochy in https://github.com/conda/conda-pack/pull/257

## New Contributors
* @saraedum made their first contribution in https://github.com/conda/conda-pack/pull/159
* @Rtanti made their first contribution in https://github.com/conda/conda-pack/pull/218
* @kenodegard made their first contribution in https://github.com/conda/conda-pack/pull/227
* @jezdez made their first contribution in https://github.com/conda/conda-pack/pull/233
* @jjhelmus made their first contribution in https://github.com/conda/conda-pack/pull/252
* @andysham made their first contribution in https://github.com/conda/conda-pack/pull/275
```

**Review by jaimergp — APPROVED** [review]

**Pull request merged**
